### ISSUE TITLE
HTML file without <html>, <head>, and <body> tags pass validation

### ISSUE THREAD

**Issue by egillespie** [htmlhint/HTMLHint#1020]
**Describe the bug**

The `htmlhint` linter reports no errors when an HTML file containing a DOCTYPE and tags other than `<html>`, `<head>`, and `<body>`.

**To Reproduce**

1. Create a file named `index.html`
2. Put the following content in it:
    ``` html
    <!DOCTYPE html>
    <title>Testing</title>
    <h1>Testing</h1>
    ```
4. Run `htmlhint index.html`
5. See error:
    ~~~
    Scanned 1 files, no errors found (9 ms).
    ~~~
6. The exit code is also `0`

**Expected behavior**

`htmlhint` should return a non-zero exit code and report that the HTML file is missing the required `<html>`, `<head>`, and `<body>` tags.

**Screenshots**

<img width="640" alt="Screenshot of index.html file described in the Steps to Reproduce and the unexpected output and exit code of zero" src="https://user-images.githubusercontent.com/5572255/168404594-b6c8e05d-f1b4-48a8-a279-a02ba45968cc.png">

**Versions:**

I have reproduced this in both `htmlhint` versions 1.1.2 and 1.1.4 (the latest version as of creating this issue).

**Comment by nschonni** [comment]
> `htmlhint` should return a non-zero exit code and report that the HTML file is missing the required `<html>`, `<head>`, and `<body>` tags.

None of those are required by the spec https://html.spec.whatwg.org/multipage/semantics.html#the-html-element
The w3 validator will also not complain about this https://validator.w3.org/nu/#textarea
