### ISSUE TITLE
No misspelled tags check? 

### ISSUE THREAD

**Issue by OnkelTem** [htmlhint/HTMLHint#1046]
I'm just wondering how comes that it doesn't check for misspelled tags?

E.g. it's perfectly fine with this wrong HTML in the [playground](https://htmlhint-playground.netlify.app/):

```html
    <ul>
      <li>Item</li>
      <li>Item</li>
      <div>Item</div>
    </ul>
```

Probably I'm missing the main idea of this linter, but if it doesn't know about correct html, then what's the point?

**Comment by coliff** [comment]
HTMLHint isn't (and doesn't claim to be) a HTML spec validator.
You can see a list of rules here: https://htmlhint.com/docs/user-guide/list-rules

If you're after a pure HTML-spec Validator then checkout: https://github.com/validator/validator

**Comment by OnkelTem** [comment]
Hm, I see, thanks. Well, I actually use HTMLHint in VSCode. 
It would be greate to have validator in VSCode, but I couldn't find a single one. So currently neither VSCode nor any of its extension doesn't know that `<div>` shouldn't nbe in `<ul>`.
