### ISSUE TITLE
Update Node versions used on GitHub Actions

### ISSUE THREAD

**Issue by coliff** [htmlhint/HTMLHint#1202]
I suggest we drop Node v17 and maybe v14 and add v18.

For reference here are the currently supported Node versions:
https://github.com/nodejs/release#nodejs-release-working-group

**Comment by nschonni** [comment]
👍  to dropping 17, 👎 on 14 since it doesn't hit EOL till April 2023
Also good adding 18 (and 19 as of today)

**Comment by nschonni** [comment]
Would probably make sense to add `engines` to `package.json` to be explicit about the supported/tested versions
