### ISSUE TITLE
Improve documentation of `tags-check`

### ISSUE THREAD

**Issue by groenroos** [htmlhint/HTMLHint#1211]
[The current documentation](https://htmlhint.com/docs/user-guide/rules/tags-check) of the `tags-check` rule is quite spartan, in that it doesn't explain in full the built-in constraints it checks for, or the way or format in which the end user project can extend or override these constraints.

I was able to understand the feature better (what exactly it does, how it can be customised, and what attributes are available) by reading the source code, but ideally these details would be included in the documentation as well.

**Comment by varun-khachane** [comment]
Hi, I would like to work on this issue. Can you please assign it to me ?
