### ISSUE TITLE
attr-whitespace not detected

### ISSUE THREAD

**Issue by MartaGD** [htmlhint/HTMLHint#1212]
Hi,
**Describe the bug**
We are having problems because the plugin is not detecting the attr-whitespace error but the server Jboss7 is detecting it and we can only solve it one by one because of the error log.

**To Reproduce**
1. Install the HTMLHint plugin 
2. Open the Problems view in our page, in this case a .jsp  (we already added JSP to the settings.json under document,selector)
3. We compile the proect and the server give us the error
_Caused by: org.apache.hasper.JasperException:/Web-INF/gestionarCampana/gestionarCamapana.jsp (JWEB004251: An error occurred at line: 199 column: 79) jsp.error.attribute.nowhitespace_
5. Even though the attr-nowhitespace do not appear in the problems view.
![image](https://user-images.githubusercontent.com/17433636/198604230-639d9129-e39c-4c6d-bbdb-d230e51ff247.png)

**Expected behavior**
The attr-whitespace that appears in the documentation https://htmlhint.com/docs/user-guide/rules/attr-whitespace should be detected when there is no space between two attributes.

Thank you

**Comment by nschonni** [comment]
No, that rule flags trailing/leading space inside an attribute value. None of the attribute rules deal with the case you're describing https://htmlhint.com/docs/user-guide/list-rules#attributes
