### ISSUE TITLE
How to watch files ?

### ISSUE THREAD

**Issue by edouard-lopez** [htmlhint/HTMLHint#135]
Is there a flag to watch files/directories? As I put this in my _package.json_ but it a one shot:

```
  "scripts": {
    "watch:quality": "htmlhint --config htmlhintrc  *.html",
}
```

**Comment by yaniswang** [comment]
You can use grunt-htmlhint.

**Comment by edouard-lopez** [comment]
@yaniswang I'm stop using gulp/grunt and use bare [NPM script in my package.json](https://github.com/11h42/11H42.com/blob/gh-pages/package.json).

**Comment by gonzoyumo** [comment]
@edouard-lopez it's a bit late but in case someone else ends here: you can use chokidar CLI (https://github.com/kimmobrunfeldt/chokidar-cli) to watch needed files and run arbitrary command. 
e.g:
```
"qa:html": "htmlhint ./src/**/*.html",
"qa:html:watch": "SHELL=/bin/bash chokidar --initial --silent './src/**/*.html' -c 'npm run qa:html'",
```
