### ISSUE TITLE
Custom rules not working

### ISSUE THREAD

**Issue by LucEnden** [htmlhint/HTMLHint#1381]
**Describe the bug**
None of my custom rules seem to work.

Bellow is a testing rule I have setup (`linting/htmlhint/no-div.js`):
```javascript
module.exports = HTMLHint => {
    HTMLHint.addRule({
        id: 'no-div',
        description: 'Description of my rule',
        init(parser, reporter) {
            const self = this;
            parser.addListener('tagstart', event => {
                const tagName = event.tagName.toLowerCase();
                if (tagName === 'div') {
                    reporter.warn('Do not use divs!', event.line, event.col, self, event.raw);
                }
            });
        },
    });
};
```

`.htmlhintrc`:
```json
{
    "rulesdir": ["linting/htmlhint"],
    "no-div": true,
    "tagname-lowercase": false,
    "attr-lowercase": false,
    "attr-value-double-quotes": true,
    "doctype-first": false,
    "tag-pair": true,
    "spec-char-escape": true,
    "id-unique": true,
    "src-not-empty": true,
    "attr-no-duplication": true,
    "title-require": true
}
```

test file (`test.html`):
```html
<div>test</div>
```

I run `npx htmlhint`, which finds the right config file, but my rule does not trigger.

**To Reproduce**

1. Use `npm install --save-dev htmlhint@1.1.4`
2. Recreate the file structure as described in the description
3. run `npx htmlhint`, which finds the right config file, but my rule does not trigger.
4. No linting errors reported

**Expected behavior**
An error should be reported that I am using a div

**Screenshots**
![image](https://github.com/htmlhint/HTMLHint/assets/64869906/9a91bd01-10fe-43e9-a68e-85a9bb90fe44)

Edit: I already tried the following;
- Using differnet paths for the `rulesdir` option
- Different implementations for my rule file

**Comment by terenc3** [comment]
You need to provide the rulesdir via cli not configuration file e.g. `npx htmlhint --rulesdir linting/htmlhint/`

**Comment by LucEnden** [comment]
> You need to provide the rulesdir via cli not configuration file e.g. `npx htmlhint --rulesdir linting/htmlhint/`

I will be trying this tonight

**Comment by LucEnden** [comment]
> I will be trying this tonight
The error persists when specifying the rules dir via the CLI
![image](https://github.com/htmlhint/HTMLHint/assets/64869906/94481310-8512-43ca-91f3-60472533e417)

**Comment by LucEnden** [comment]
> @LucEnden did you find out a solution? i'm trying to add custom rules & i got the same result as you

I opted to use custom logic (Python script) to implement my linting. I have removed HTMLHint from my application

So no, I did not find a solution for this particular problem.
