### ISSUE TITLE
self-closed custom-element do not fail. 

### ISSUE THREAD

**Issue by MeirionHughes** [htmlhint/HTMLHint#142]
https://www.w3.org/TR/html-markup/syntax.html#syntax-elements

> A non-void element must have an end tag, unless the subsection for that element in the HTML elements section of this reference indicates that its end tag can be omitted.

So custom tags webcomponents must have an end tag and cannot self-close. 

example `htmlhint --rules tag-pair`

```
<custom-element attribute="value"/>
```

should fail in htmlhint (currently does not)  

```
<custom-element attribute="value"></custom-element>
```

should pass in htmlhint (currently does)

**Comment by joeskeen** [comment]
+1

I also found this which is useful:

> The following is a complete list of the void elements in HTML:
>    area, base, br, col, command, embed, hr, img, input, keygen, link, meta, param, source, track, wbr

<https://www.w3.org/TR/html-markup/syntax.html#syntax-elements>

Currently HTMLHint doesn't complain if you self-close any element.  We had an issue in one of our projects where there was a self-closing `textarea` which caused some really weird behavior [during minification](https://github.com/kangax/html-minifier/issues/695) and runtime.

Thus it would be great if we could have a rule that would cause a warning for any self-closing tag that isn't in the list of void tags above.

**Comment by schmod** [comment]
Just wanted to say that we've had a similar issue, where htmlhint failed to correctly mark `<div />` as invalid.
