### ISSUE TITLE
& is not identified as a special char that needs escaping

### ISSUE THREAD

**Issue by rbanffy** [htmlhint/HTMLHint#143]
"&" is not identified as a special character that needs escaping. When running with the spec-char-escape rule enabled, the program fails to flag isolated "&"s, in strings such as "Q&A"

**Comment by yaniswang** [comment]
You must use : `Q&amp;A`

![image](https://cloud.githubusercontent.com/assets/970390/15560770/43d9cea6-2321-11e6-8f5f-f4b498e76129.png)

**Comment by rbanffy** [comment]
I know that, but a linter should point that out.

**Comment by yaniswang** [comment]
I'm sorry, i forget HTMLHint not support it.
Next  version try to add this.

**Comment by rbanffy** [comment]
If you don't mind, I can start writing the tests

**Comment by rbanffy** [comment]
The test is on https://github.com/yaniswang/HTMLHint/pull/144 (and merging it breaks the build)
