### ISSUE TITLE
'attr-value-double-quotes' when set to false should check for single quotes instead?

### ISSUE THREAD

**Issue by alallier** [htmlhint/HTMLHint#147]
Right now when `attr-value-double-quotes` is set to true it checks to see if attribute values are in double quotes. But when it is false it doesn't check presence of quotes at all. I assume a more intuitive implementation would be that when specified as false that it would check for single quotes instead.

**Comment by PhiLhoSoft** [comment]
I disagree. People should be allowed to omit quotes if they want (and if they can, of course!), or to mix quotes if that's what they like (or if it fits a need).
Another rule to enforce single quote is preferable.
I see @JustinDFuller made a PR following this idea, BTW...

**Comment by JustinDFuller** [comment]
Thanks @PhiLhoSoft @alallier @yaniswang We have a PR (that passed tests) for this issue, if people are agreed on the implementation could we look at accepting it?

**Comment by alallier** [comment]
I agree the new rule is good. Although a friend of mine tried to implement this before and it was never accepted see #66

**Comment by Shinigami92** [comment]
In my opinion, we should put `attr-value-double-quotes` and `attr-value-single-quotes` into a rule together `attr-value-quotes` and make the options more extensible

```json
{
  "attr-value-quotes": [true, { "quote": "single", "severity": "warning" }]
}
```

The value `true` or `false` should only indicate whether the rule is active or not

This will make #154 obsolete
