### ISSUE TITLE
Parsing handlebars templates

### ISSUE THREAD

**Issue by blandine** [htmlhint/HTMLHint#15]
Hi !
Thanks for your work, it's a useful tool.
I've started to implement handlebars template parsing, but I wonder if it has to be in HTMLHint or should I create an HbsHint. Being in HTMLHint involves a lot of changes in code, so I'm not sure if it's a good idea or not. 
What do you think about it ?
Thanks

**Comment by bitfed** [comment]
Brackets is still in need of a solution for validating handlebars.  I've not delved deep enough to know the rules are terribly different from HTML.

Would a setting (such as /*jslint node:true */) in a comment decrease the redundancy of creating two separate plugins and allow you to just add the support needed to remove irrelevant hints?

Like a "handlebars mode".  I'm not sure though if there is a way to disable your plugin for HTML (such as if someone wanted to use W3C Validatioin instead) while keeping it enabled for handlebars.

Thanks
