### ISSUE TITLE
Feature request: rule to check level of indents

### ISSUE THREAD

**Issue by necramirez** [htmlhint/HTMLHint#153]
The indent rule [`space-tab-mixed-disabled`](https://github.com/yaniswang/HTMLHint/wiki/space-tab-mixed-disabled) recently supported checking the indent length when using spaces. https://github.com/yaniswang/HTMLHint/issues/73#event-646670235

However, it only checks if the number of spaces is a multiple of the value specified in the rule. That is, if I specify `space2`, it only checks if the number of spaces is an even number. For example, if I configured `space2`, this is correct:

```
<html>
  <head>
    <title>Title</title><!-- has 4 spaces -->
  </head>
</html>
```

This is correctly marked as an error:

```
<html>
  <head>
   <title>Title</title><!-- has 5 spaces -->
  </head>
</html>
```

But these are not marked as errors:

```
<html>
  <head>
<title>Title</title><!-- not indented at all! -->
  <title>Title</title><!-- same indent level -->
      <title>Title</title><!-- over-indented -->
  </head>
</html>
```

**Comment by monisnap-julien** [comment]
Hello,
Any news on this ? It's a feature that we can found in Vetur (vue.js extension) and it's really usefull to keep consistent and clean code.
