### ISSUE TITLE
ignore comment?

### ISSUE THREAD

**Issue by sinedied** [htmlhint/HTMLHint#161]
Is there currently a way to add `ignore` comment, to skip linting for specific lines or files, like jshint or others, for example:

<!-- htmlhint:ignore start>
...
<!-- htmlhint:ignore end>

**Comment by jaepage** [comment]
This issue is approaching two years' age, with over a dozen thumbs up, but no comment. Is this repo maintained, please?

**Comment by hacknug** [comment]
@jaepage no it's not, unfortunately 😞

**Comment by jaepage** [comment]
Not to go too far on a tangent here, but would you know of another Sublime linter for HTML that is maintained?

**Comment by hacknug** [comment]
Google sent me here https://github.com/SublimeLinter/SublimeLinter-html-tidy

**Comment by jaepage** [comment]
I recently filed an issue there regarding that plugin's failure to work at all.

**Comment by grantfoster** [comment]
This is an absolute necessity.

**Comment by xianshenglu** [comment]
The syntax can be like  `<!--htmlhint disable-->`, `<!--htmlhint enable-->`, `<!--htmlhint disable-next-line -->`.

**Comment by mcm-ham** [comment]
Good issue to add keep-unstale label too?
