### ISSUE TITLE
Feature Request: Extend another .htmlhintrc file

### ISSUE THREAD

**Issue by andrewvaughan** [htmlhint/HTMLHint#162]
Similar to how [ESLint](http://eslint.org/docs/user-guide/configuring) allows for `extends` variables to allow a file to extend another hint configuration, it would be helpful to have HTMLHint support extension.

We use this specifically in the case where we have many projects that follow the same .htmlhintrc configuration, but might require a slight change for a specific case (which is not worth rewriting the entire .htmlhintrc file, much less maintaining them amongst dozens of projects).

**Comment by alan-agius4** [comment]
Still nothing about this?

**Comment by ntdaley** [comment]
Would be especially useful if we could extend a nodejs module that contained the other config file.  (As can be done with tslint).

**Comment by nebulousdog** [comment]
@ntdaley agreed! the old work towards this got abandoned I think :grimacing: 

here I think? https://github.com/htmlhint/HTMLHint/pull/286

**Comment by Shinigami92** [comment]
Is #279 solving this? Or is more wanted?

**Comment by nebulousdog** [comment]
@Shinigami92 if I understand correctly, yes this is a subset request of the big #279 list.

**Comment by nebulousdog** [comment]
:weary:
