### ISSUE TITLE
HTML link tag false positive - Special characters must be escaped : [<]

### ISSUE THREAD

**Issue by jchell** [htmlhint/HTMLHint#165]
**Issue:** I believe the < and > characters are being caught as a special character that requires escaping when it shouldn't for html files.

**Screenshot:**
![image](https://cloud.githubusercontent.com/assets/8511405/17905184/b1dff8b0-6937-11e6-93ba-aae213b2cc62.png)

**Comment by yaniswang** [comment]
Bad code: `<link rel-""`

**Comment by jchell** [comment]
Hi Yanis,

Good point. Thanks for that, however this is a different error than escaped special characters.

Regards,
John Hellman

**Comment by sopanhavuth-aka-sam** [comment]
I'm having similar problem with <a> tag

**Comment by Pomax** [comment]
still running into this, the problem seems to be that HTMLHint is not flagging the correct error. While it should be saying "attribute name cannot be followed by `-`" or more generically "attribute name must be followed by `=`, white space, or `>`" it is instead reporting the error with an unrelated error message. This means that people still don't know what's actually wrong, and need to go through the same steps of debugging their code that they would if they weren't using HTMLHint.

**Comment by Taitdanielle** [comment]
So, I see this issue is still ongoing, I currently have it.

**Comment by Pomax** [comment]
This absolutely still needs someone to verify it still exists, and if it does, land a fix for it. Error reporting should tell the user what's wrong, not lead them on a wild goose chase ending in a red herring.

**Comment by Pomax** [comment]
This absolutely still needs someone to verify it still exists, and if it does, land a fix for it. Error reporting should tell the user what's wrong, not lead them on a wild goose chase ending in a red herring.

**Comment by edarioq** [comment]
Just got this linting an Angular app on an HTML file, any fix ?

**Comment by wpeguero** [comment]
I am also encountering this issue.

**Comment by sxp2high** [comment]
Any solution to this yet? This has been happening for me for months.

Whenever it happens I have to restart VS Code and it's fine for a short while, but at some point it always returns.

![escaped](https://user-images.githubusercontent.com/2714536/123978423-22756800-d9c0-11eb-9d29-e2f8306b5fd2.jpg)

**Comment by oprisyazhnaya** [comment]
Я тоже сталкиваюсь с этой проблемой.

**Comment by Pomax** [comment]
Note that this issue got closed, so instead of replying it's infinitely better to create a new issue with your specific reproducible use-case.
