### ISSUE TITLE
Tag must be paired, no start tag: [</iframe>]

### ISSUE THREAD

**Issue by pattrickrice** [htmlhint/HTMLHint#168]
False error of no start tags

![image](https://cloud.githubusercontent.com/assets/20763171/18257070/cfc2400a-7372-11e6-97d9-a60598aeb9ab.png)

**Comment by 4kochi** [comment]
Have the same problem. In my case the error occurs when there are braces in the attributes.

```
<my-button name="cancel" (action)="reset()"></my-button> // throws error
<my-button name="cancel" [disabled]="disabled"></my-button> // throws error
<my-button name="cancel"></my-button> // works fine
```

**Comment by SqrTT** [comment]
On screenshot typo make place, space is required between `height` and `width` attribute.

**Comment by thedaviddias** [comment]
Hey @pattrickrice and @4kochi, this is still an issue? If not can you close the ticket please?
