### ISSUE TITLE
Google Polymer "$" attribute binding brakes spec-char-escape rule in vscode

### ISSUE THREAD

**Issue by ppatotski** [htmlhint/HTMLHint#172]
Turned on:
![image](https://cloud.githubusercontent.com/assets/21025786/19000399/57b97ff4-8710-11e6-920d-c85024f5fd47.png)

Turned off:
![image](https://cloud.githubusercontent.com/assets/21025786/19000388/3f111b7e-8710-11e6-99f3-2e690e473b2b.png)

**Comment by yaniswang** [comment]
Show your htmlhint version?

Please update to new version first.

**Comment by ppatotski** [comment]
Thanks for quick response.
Version in node_modules/htmlhint/package.json: 0.9.13
Version shown in Extensions panel of VSCode: 0.0.3
Node version: 6.5.0
OS: Windows 8

**Comment by yaniswang** [comment]
http://htmlhint.com/

Test it on the site, it show no error

**Comment by ppatotski** [comment]
Bug is reproducible in Visual Studio Code. It recognizes any of +`~!#@%$ as a special character. Can you please try `<div $ somestuff="stuff"></div>` in your VSCode?

**Comment by yaniswang** [comment]
I have not install VS Code.
HTMLHint v0.9.13 can support your code

![image](https://cloud.githubusercontent.com/assets/970390/19017795/e788e712-887a-11e6-803b-78f1abc3280e.png)

**Comment by ppatotski** [comment]
Yes, it works fine on test page. Bug is reproducible in vscode. I have corrected issue title for clarity. Thanks.

**Comment by ppatotski** [comment]
I found temp workaround here [.](https://github.com/Microsoft/vscode-htmlhint/issues/13)

> A quick fix is to go to the extension's folder (e. g., c:\Users\<USER>\.vscode\extensions\mkaufman.HTMLHint-0.0.3\server\ on Windows) and execute the following commands there:
> npm i htmlhint@latest
