### ISSUE TITLE
Ability to plugin custom rules in htmlhintrc file like stylelint and eslint

### ISSUE THREAD

**Issue by inspiraller** [htmlhint/HTMLHint#178]
Like similar linting plugins - eslint, stylelint and so forth it would be really useful for a developer to add a custom rule in the htmlhintrc file like this:

```
{
	"plugins": [		
		"./htmlhintCustomRules/steves/rule1/index.js",
	],
	rules:{
		"tag-pair": true,
		"steves-rule1":true
	}
}

```

Currently in order to create a custom rule it looks like a developer will have to add a file to the src/rules/ directory in the master source.  Then generate the output htmlhint using grunt. Or make a change request to approve a new rule. This reduces interest and technical understanding how to create a basic rule on a project per project basis.

**Comment by ptitgraig** [comment]
+1

**Comment by pmcelhaney** [comment]
Looks like the cli already has a `--rulesdir` option. It's just not documented very well.

**Comment by jgarite** [comment]
Would this be the way to add a rule for something like:
"ctrl" must be prefixed with $

ctrl.test = fail
$ctrl.test = pass

**Comment by thedaviddias** [comment]
Duplicate with #167

**Comment by mohammedzamakhan** [comment]
@pmcelhaney we should be able to add the directory or the rules files or rules npm package directly in .htmlhintrc file

**Comment by nebulousdog** [comment]
Are we able to do this with the `.htmlhintrc` file so that linters pick this up? Right now my custom rules only can be picked up when running via cli as @pmcelhaney mentioned in https://github.com/htmlhint/HTMLHint/issues/178#issuecomment-313794448.

**Comment by nebulousdog** [comment]
stale bot, chill 😎

**Comment by nebulousdog** [comment]
:weary:

**Comment by JaredSartin** [comment]
pinging this again.
