### ISSUE TITLE
Error for camelcase `viewBox` attribute which is case-sensetive in SVG

### ISSUE THREAD

**Issue by marcoms** [htmlhint/HTMLHint#183]
`viewBox` must be typed with a capital `B` as SVG uses case sensitive attributes as far as I know, yet HTMLHint reports an error for inline SVG.

**Comment by aaronkahlhamer** [comment]
Correct. There is a solution. See [item 3](https://github.com/yaniswang/HTMLHint/wiki/Attr-lowercase) under 'config value'. 

Besides viewBox, SVG has many other camelCase attributes. Feel free to copy the code from [the journal](https://medium.com/@networkaaron/dev-diary-svg-htmlhint-attr-lowercase-2a84a563eb01#.wvjtw2ogk).

**Comment by bugproof** [comment]
this should be whitelisted by default...
