### ISSUE TITLE
[new rule] Max-Len to restrict the length of the line

### ISSUE THREAD

**Issue by hamxabaig** [htmlhint/HTMLHint#185]
I'd like to propose a new rule which makes sense i guess and that is to restrict the length of the Line.  When we've long lines it creates the vertical scrollbar in IDE's and Editors and it makes it difficult to read the code.
We can have something like ESLINT `max-len` rule where we can control the length of line.

Following will be error:
```
/*html hint max-len: ["error", 80] */
<input type="text" name="longnameofinput" id="longidofinput" maxlength="10" class="form-control" >
```
Following will be fine:
```
/*html hint max-len: ["error", 80] */
<input 
    type="text" name="longnameofinput"
    id="longidofinput" maxlength="10"
    class="form-control"
>
```

**Comment by alan-agius4** [comment]
+1 this would be extremly usful

**Comment by handonam** [comment]
+1 on this as well.

**Comment by AbdealiJK** [comment]
+1 on this :)
Wondering if this is planned or if I can help in bringing this forward ?

**Comment by thedaviddias** [comment]
Hi @hamxabaig, you can propose a PR if you want :)

**Comment by jkevingutierrez** [comment]
+1
