### ISSUE TITLE
Running htmllint as package.json script with --config causes Config loaded: .htmlhintrc

### ISSUE THREAD

**Issue by graph1994** [htmlhint/HTMLHint#187]
I added htmlhint a lint script on package.json and it causes Config loaded: .htmlhintrc to be spammed in the console
Here what I have: 
 ` "lint": "eslint --ext .js,.vue src test/unit/specs test/e2e/specs && node_modules/htmlhint/bin/htmlhint --config .htmlhintrc  **/**/*.vue"`
![screen shot 2017-01-06 at 9 43 37 am](https://cloud.githubusercontent.com/assets/6313246/21721505/b23bae38-d3f6-11e6-8fe4-fa739b0336a4.png)

**Comment by marcoostan** [comment]
+1

I have the same problem. Who can help us?

**Comment by marcoostan** [comment]
I have some informations to complete.

If I run `./node_modules/.bin/htmlhint ./src/**/*.html`, It will get all erros in all HTML files.
But, if I run It with any other extension, I get the this issue.

I need to run file per file with any other extension different of HTML to works fine.

**Comment by gagarine** [comment]
The configuration is ignored on my side. In my package.json try:
` "lint:html": "htmlhint --config .htmlhintrc src/**/*.html;"`
` "lint:html": "htmlhint --config ./.htmlhintrc src/**/*.html;"`
` "lint:html": "htmlhint src/**/*.html;"`
` "lint:html": "htmlhint --config htmlhintrc.conf src/**/*.html;"`

Nothings wokrs and the default is taken instead of my configuration.

**Comment by tirithen** [comment]
I have the same problems when trying to run from bash I tried

node_modules/.bin/htmlhint --ignore bower_components/**

But it still lints inside bower_components and also ignores to use the rules I have set inside my .htmlhinrrc file

**Comment by tirithen** [comment]
Ok, the problem with not reading .htmlhintrc was because of a syntax error in the file without any kind of error message shown

**Comment by msdundar** [comment]
Running path part of the command with single quotes fixes the problem. Ie:

```bash
yarn exec htmlhint --config .htmlhintrc 'app/views/**/*.html.erb'
```

**Comment by vsvipul** [comment]
We are facing the same issue [here](https://github.com/zulip/zulip-electron/pull/726). Using single quotes makes it work only on Ubuntu and doesn't work for windows. Any help here? ping @msdundar

**Comment by vsvipul** [comment]
Worked for both Windows and Linux after changing the npm command to something like this -
```
    "lint-html": "./node_modules/.bin/htmlhint \"app/renderer/*.html\" ",
```
and then running 
```
npm run lint-html
```
