### ISSUE TITLE
Cut a relase for 0.9.14

### ISSUE THREAD

**Issue by nikolasleblanc** [htmlhint/HTMLHint#198]
https://github.com/yaniswang/HTMLHint/commit/d6c8876f13af4bd6c90326667a38b0a4a01c19cb

Has a change to the jshint dep (bumping it to 2.9.4), and your package.json has a version of 0.9.14, but npm tops out at 0.9.13, which still has jshint@2.8.0.

**Comment by dpilafian** [comment]
Publishing next version on `npm` will fix security warnings for a lot of people:

| High | Regular Expression Denial of Service |
|---|---|
| Package       | minimatch                                                    |
| Patched in    | >=3.0.2                                                      |
| Dependency of | gulp-htmlhint [dev]                                          |
| Path          | gulp-htmlhint > htmlhint > jshint > minimatch                |
| More info     | https://nodesecurity.io/advisories/118                       |
