### ISSUE TITLE
The id and class attribute values must be in lowercase and split by a dash.

### ISSUE THREAD

**Issue by tayfunyasar** [htmlhint/HTMLHint#199]
http://i.imgur.com/TkjabAQ.png

It says that I need to use lowercase but it is already lowercased.

Whats the problem?

`<input id="checkbox-leftselectitem-{{$index}}" type="checkbox" checklist-model="self.leftSelectedItems" checklist-value="item" />`

I also tried

`<input id="checkbox-leftselectitem-{{$index}}" type="checkbox" checklist-model="self.leftselecteditems" checklist-value="item" />`

**Comment by hepcat72** [comment]
So is there a way to appease the linter in this scenario, or is this a bug for which we need to add an ignore statement?  I have the same issue with using a template variable for the `id` attribute.

**Comment by coliff** [comment]
The reason is that HTMLHint was only intended to be run on final, complete, compiled HTML for the browser and as such isn't optimised to be run on partials/templates languages/framworks such as Angular, Nunjuks, Liquid or Hugo/Jekyll theme templates etc.

So the `id-class-value` rule is actually saying the id must ONLY contain lowercase letters and split by a dash and must not contain any special characters.

**Comment by coliff** [comment]
Personally, I have a `.htmlhintrc` config with stripped down rules optimised just for testing partials (I do a lot of Hugo site work which also has a lot of {{ }}). I keep that in my directory of partials so I get real-time linting from VS Code.

I then have another full `.htmlhintrc` config in the projects root and then I have a lint-html script in my `package.json` (`"lint-html": "htmlhint \"build/**/index.html\"",`) which I can then run on my final, minified and compiled HTML.

Works great and means HTML code is tested at two stages of development. :-)

**Comment by hepcat72** [comment]
Do you have any guidance on stripped down rules for testing partials?  Currently, I don't think we have any html files that aren't templates, but I see how that hierarchical config would be useful.  We decided we would just disable rules as we run afoul of them.

**Comment by coliff** [comment]
partials:
```
{
  "alt-require": true,
  "attr-lowercase": false,
  "attr-no-duplication": false,
  "attr-unsafe-chars": true,
  "attr-value-double-quotes": false,
  "attr-value-not-empty": false,
  "doctype-first": false,
  "doctype-html5": true,
  "head-script-disabled": false,
  "href-abs-or-rel": false,
  "html-lang-require": true,
  "id-class-ad-disabled": true,
  "id-class-value": false,
  "id-unique": false,
  "inline-script-disabled": false,
  "inline-style-disabled": false,
  "space-tab-mixed-disabled": false,
  "spec-char-escape": false,
  "src-not-empty": true,
  "style-disabled": false,
  "tag-pair": false,
  "tag-self-close": false,
  "tagname-lowercase": true,
  "title-require": false
}
```

compiled, minified HTML

```
{
  "alt-require": true,
  "attr-lowercase":
    [
    "allowReorder",
    "attributeName",
    "attributeType",
    "autoReverse",
    "baseFrequency",
    "baseProfile",
    "calcMode",
    "clipPathUnits",
    "contentScriptType",
    "contentStyleType",
    "diffuseConstant",
    "edgeMode",
    "externalResourcesRequired",
    "filterRes",
    "filterUnits",
    "glyphRef",
    "gradientTransform",
    "gradientUnits",
    "kernelMatrix",
    "kernelUnitLength",
    "keyPoints",
    "keySplines",
    "keyTimes",
    "lengthAdjust",
    "limitingConeAngle",
    "markerHeight",
    "markerUnits",
    "markerWidth",
    "maskContentUnits",
    "maskUnits",
    "numOctaves",
    "onBlur",
    "onChange",
    "onClick",
    "onFocus",
    "onKeyUp",
    "onLoad",
    "pathLength",
    "patternContentUnits",
    "patternTransform",
    "patternUnits",
    "pointsAtX",
    "pointsAtY",
    "pointsAtZ",
    "preserveAlpha",
    "preserveAspectRatio",
    "primitiveUnits",
    "refX",
    "refY",
    "repeatCount",
    "repeatDur",
    "requiredExtensions",
    "requiredFeatures",
    "specularConstant",
    "specularExponent",
    "spreadMethod",
    "startOffset",
    "stdDeviation",
    "stitchTiles",
    "surfaceScale",
    "systemLanguage",
    "tableValues",
    "targetX",
    "targetY",
    "textLength",
    "viewBox",
    "viewTarget",
    "xChannelSelector",
    "yChannelSelector",
    "zoomAndPan"
  ],
  "attr-no-duplication": true,
  "attr-unsafe-chars": true,
  "attr-value-double-quotes": false,
  "attr-value-not-empty": false,
  "doctype-first": false,
  "doctype-html5": true,
  "head-script-disabled": false,
  "href-abs-or-rel": false,
  "html-lang-require": false,
  "id-class-ad-disabled": true,
  "id-class-value": false,
  "id-unique": false,
  "inline-script-disabled": false,
  "inline-style-disabled": false,
  "space-tab-mixed-disabled": false,
  "spec-char-escape": false,
  "src-not-empty": true,
  "style-disabled": false,
  "tag-pair": false,
  "tag-self-close": false,
  "tagname-lowercase": true,
  "title-require": true
}

```
