### ISSUE TITLE
Illogical Problem HTML Hint

### ISSUE THREAD

**Issue by Tes3awy** [htmlhint/HTMLHint#209]
I use your extension and it's pretty much amazing to have an extension like HTMLHint. However, I always get a strange and illogical problem hint. The problem is shown in the image below. I don't know how come the "$" be not defined!.

![htmlhint](https://user-images.githubusercontent.com/11368432/26956610-4bc99baa-4cbf-11e7-8351-c40e76339cb5.PNG)

**Comment by SidneyNemzer** [comment]
I'm guessing HtmlHint won't check that you have jQuery installed (that would be amazing, but I don't know any linters that do that).

You might be able to git rid of this error by adding `/* global $ */` as the first line of that script tag

That's a special comment that you can use to tell linters about global variables.
