### ISSUE TITLE
Inline rules only work in the first line of a file

### ISSUE THREAD

**Issue by lukaw3d** [htmlhint/HTMLHint#210]
Inline rules don't work unless they appear on the first line of a file.

I think it might just be that this regex needs a multiline flag https://github.com/yaniswang/HTMLHint/blob/master/src/core.js#L40
```diff
- html = html.replace(/^\s*<!--\s*htmlhint\s+([^\r\n]+?)\s*-->/i, function(all, strRuleset){
+ html = html.replace(/^\s*<!--\s*htmlhint\s+([^\r\n]+?)\s*-->/im, function(all, strRuleset){
```

**Comment by krank** [comment]
Would be a very nice change, as it would allow specific blocks to be excluded or included from being checked against specific rules. Like php blocks for instance...
