### ISSUE TITLE
All errors in the file are displayed for line #1 if the file uses Macintosh line breaks i.e., CF

### ISSUE THREAD

**Issue by yprasad1** [htmlhint/HTMLHint#215]
All errors in the file are displayed for line 1 if the file uses Macintosh line breaks i.e., CF.
For example, the attached file has 4 errors. All the 4 messages are displayed for line 1.
![htmlhint](https://user-images.githubusercontent.com/28131566/29016738-5898122c-7b71-11e7-88ee-8309b1762467.png)

Test Files: 
[TestFile.zip](https://github.com/yaniswang/HTMLHint/files/1204145/TestFile.zip)

**Comment by Sufiyaaan** [comment]
I think the instead of <!doctype html> it should be <!DOCTYPE html>
