### ISSUE TITLE
Can HTMLHint be used with angular and other frameworks?

### ISSUE THREAD

**Issue by dinuish94** [htmlhint/HTMLHint#228]
When I ran the the HTMLHint tool on an angular project, it gave an issue saying "ng-app must be in double quotes". Does this mean that HTMLHint  can only be run for pure HTML files?

**Comment by Shinigami92** [comment]
Here my .htmlhintrc for AngularJS projects
```json
{
	"attr-lowercase": true,
	"attr-no-duplication": true,
	"attr-unsafe-chars": true,
	"attr-value-double-quotes": true,
	"doctype-first": false,
	"doctype-html5": true,
	"id-class-ad-disabled": true,
	"id-class-value": "dash",
	"id-unique": true,
	"inline-style-disabled": false,
	"space-tab-mixed-disabled": "tab",
	"spec-char-escape": true,
	"src-not-empty": true,
	"style-disabled": true,
	"tag-pair": true,
	"tag-self-close": false,
	"tagname-lowercase": true,
	"title-require": true,
	"csslint": {
		"display-property-grouping": true,
		"known-properties": true
	},
	"jshint": {}
}
```

Just put this content in an .htmlhintrc in your project's directory
Maybe install a plugin for your IDE/Editor and it will recognize this file

**Comment by scipper** [comment]
what about expressions in `id` for example? When I lint this code:

`<div id="{{ navigationItem.id }}"></div>`

the error 

> The id value [ {{ navigationItem.id }} ] must be unique. [error/id-unique]

is thrown. When I have an expression like: 

`<span>{{ $ctrl.timer > 0 ? 'A' : 'B' }}</span>`

I get

> Special characters must be escaped : [ > ]. [error/spec-char-escape]

This is really annoying, because it's valid AngularJs.

**Comment by AbdealiJK** [comment]
I just evaluated this on a angular project I have and based on the false positives I saw, the following works for me:
```json
{
    "attr-lowercase": false,  // cannot handle - `<ng-template [ngIf]="isVisible">`
    "attr-no-duplication": true,
    "attr-unsafe-chars": true,
    "attr-value-double-quotes": true,
    "doctype-first": false,  // Unable to handle HTML templates for components
    "doctype-html5": true,
    "id-class-ad-disabled": true,
    "id-class-value": false, // cannot handle - `<div class="{{card.css}}"></div>`
    "id-unique": false, // cannot handle -
                        // <li *ngIf="isEdit"> <a id="id1">id1</a> </li>
                        // <li *ngIf="!isEdit"> <span id="id1">id1</span> </li>
    "inline-style-disabled": true,
    "space-tab-mixed-disabled": "space2",
    "spec-char-escape": true,
    "src-not-empty": true,
    "style-disabled": true,
    "tag-pair": true,
    "tag-self-close": true,
    "tagname-lowercase": true,
    "title-require": true
}
```

**Comment by WuglyakBolgoink** [comment]
Hallo @AbdealiJK 

since last month I  have some problems with `spec-char-escape`

```
line 8   col 46  Special characters must be escaped : [  &  ].
line 26  col 41  Special characters must be escaped : [  &  ].
```

and in my template we have something like this

```
<div class="legend-users">Max & Clara</div>
```

do u have the same problems now?
