### ISSUE TITLE
Problem wtih tag-pair

### ISSUE THREAD

**Issue by brianMorilla** [htmlhint/HTMLHint#237]
I have a problem with rule tag-pair. I explain:

I have this code on my web page:
 `<button id="edit" class="btn" type="button"  onclick="javascript:editFeature()" title="<?php echo __("Edit"); ?>">
                                    <img src="../img/edit.png" width="32" height="32" />
                                    <label>
                                        <?php echo __("Edit"); ?>
                                    </label>
                                </button>`

this code mark an error like this:        
</button>
^ Tag must be paired, no start tag: [ </button> ] (tag-pair)

I think the problem is on this label :

 title="<?php echo __("Edit"); ?>" 

because If I delete this, then not mark error

**Comment by linahsie** [comment]
Using the code above, the tag-pair error disappeared after removing the double quotes in "Edit" in the title attribute. Using a single quote would solve the problem. Not sure if we want to incorporate consistent styling in quotation marks.

**Comment by linahsie** [comment]
![screen shot 2019-02-23 at 7 54 08 pm](https://user-images.githubusercontent.com/17056008/53294175-3af96600-37a7-11e9-815d-07e479f86209.png)
The code above produced another warning for line 12.
