### ISSUE TITLE
id-class-value can't provide separate rules for class and id attributes

### ISSUE THREAD

**Issue by Lithl** [htmlhint/HTMLHint#244]
I prefer using camelCase for id attributes and kebab-case for class attributes, but the `id-class-value` rule can only apply one paradigm to both.

**Comment by sachin8080** [comment]
+1

**Comment by samc449** [comment]
+1

**Comment by nathanpitman** [comment]
+1

**Comment by invot** [comment]
Can we reopen this? I'd also like to follow this standard of camelCase IDs and dashed classes.
