### ISSUE TITLE
Move htmlhint.com to HTTPS

### ISSUE THREAD

**Issue by coliff** [htmlhint/HTMLHint#250]
GitHub Pages support HTTPS with custom domains now.
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

It'd be great to update the DNS so that htmlhint.com would be available on https://htmlhint.com

**Comment by thedaviddias** [comment]
Thanks @coliff for mentioning, it's done!

**Comment by yaniswang** [comment]
@thedaviddias please give me your npm account.

**Comment by tdmalone** [comment]
@thedaviddias Did something go wrong? “There is no GitHub Pages site here”

**Comment by thedaviddias** [comment]
I waiting for the .com to be transferred, but the new domain is now https://htmlhint.io (I'll make a redirection from the .com to the .io as soon as I have the transfer done.

**Comment by waldyrious** [comment]
@coliff why was this closed? I just tried to visit https://htmlhint.io and got the following warning page:

![Screen Shot 2019-08-16 at 11 34 34](https://user-images.githubusercontent.com/478237/63162235-ec23df00-c019-11e9-81db-f289bfa021eb.png)

And without https I get a "Not found" error page.

**Comment by coliff** [comment]
htmlhint.com is now available on HTTPS. That is what this issue was for and now that is resolved this issue can be closed.

I see that https://htmlhint.io/ is showing an error though.

@thedaviddias needs to get that fixed I think.
