### ISSUE TITLE
Need exceptions "tagname-lowercase": ["linearGradient"]

### ISSUE THREAD

**Issue by SathishkumarThangavel** [htmlhint/HTMLHint#263]
As svg contain tag name is  "linearGradient". So need to exclude this tag from rule `tagname-lowercase`.

Like this "tagname-lowercase": ["linearGradient"].

**Comment by Shinigami92** [comment]
I am aware of this problem

A quick fix would be to simply implement the following:

```js
if (['linearGradient'].includes(tagName)) {
  return;
}
```

But I'm thinking about a generally new, better configuration system
If you pass an array of strings in "tagname-lowercase", it will not be expandable for future changes without introducing breaking changes to the schema

**Comment by githubSathishkumar** [comment]
hi @Shinigami92 . As we are all(team mates) using your package, this temporary fix will go off with one yarn command.

we are looking for fix in next package update. Please consider this enhancement also a priority one.

**Comment by thedaviddias** [comment]
Hi @githubSathishkumar, we'll be reviewing your issue and try to launch any fix with the version 0.11.0.
