### ISSUE TITLE
Need to throw error if non-breaking space present in html files.

### ISSUE THREAD

**Issue by SathishkumarThangavel** [htmlhint/HTMLHint#273]
**Is your feature request related to a problem? Please describe.**
Yes. nonbreaking space is not visible when copy paste content and when the site is live the letter `Â` is displaying instead of whitespace.

**Describe the solution you'd like**
throw error when you detect nonbreaking space (U+00A0) in htmlfiles.

**Describe alternatives you've considered**
Manually removing by checking rendered content (html) in browser

**Additional context**
As we are working as team, this hinting option will help us a lot.

**Comment by thedaviddias** [comment]
Hi @githubSathishkumar, we are going to review your issue and try to push it to the next version.
