### ISSUE TITLE
Refactor everything to ES2016+ or better TypeScript

### ISSUE THREAD

**Issue by Shinigami92** [htmlhint/HTMLHint#277]
**Problem**
Much of the code is written in old style `es5`
But node 6+ already supports es2016 and up natively

**Describe the solution you'd like**
Convert all the code by hand into es2016

**Describe alternatives you've considered**
- Convert all code to es2016+ and use [babel](https://babeljs.io) to transpile the code down to es2016
- Convert all code to [TypeScript](http://www.typescriptlang.org) and compile the code down to es2016
TypeScript has the advantage of even better code optimization and documentation

**Additional context**
I have already started some successful experiments in this branch https://github.com/Shinigami92/HTMLHint/tree/experimental/babel-with-es2016
Also this branch is already a PR (https://github.com/thedaviddias/HTMLHint/pull/276): https://github.com/Shinigami92/HTMLHint/tree/refactoring/test/upgrade-to-es2016

[node support of ES201X](https://node.green)

**Comment by thedaviddias** [comment]
I'm more about moving to ES6 than TypeScript. We can have some advantages of TypeScript using plain JavaScript.

**Comment by glen-84** [comment]
TypeScript is amazing. I would always recommend it.

**Comment by Shinigami92** [comment]
Now when flow is dead, are you interested that I retrying to rewrite htmlhint into typescript?
I'm only willing to write code in this project when we convert it to typescript, otherwise I'm only interested in community/issue managing and reviewing.

**Comment by Shinigami92** [comment]
Referencing PRs:

- [ ]  #390
- [ ]  #392
- [ ]  #393
- [ ]  #394
- [ ]  #398

**Comment by Shinigami92** [comment]
Awaiting https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44960
