### ISSUE TITLE
Deliver HTMLHint via CDN

### ISSUE THREAD

**Issue by Shinigami92** [htmlhint/HTMLHint#281]
**Is your feature request related to a problem? Please describe.**
There is already a working version that supports HTMLHint via browser.
When we work on #277, we lose this feature :(

**Describe the solution you'd like**
Deliver an HTMLHint version that can be executed in the browser via a CDN
This allows old school HTML developers and young developers to easily add a script tag
`<script src="https://...cdn.../HTMLHint-0.10.0.min.js" />`
This inserts HTMLHint into the global scope

**Comment by Neo-Zhixing** [comment]
The code is now compiled into a umd package. Now this can be done by writing:
```html
<script src="https://cdn.jsdelivr.net/npm/htmlhint@latest/dist/htmlhint.js"></script>
<script>
  let messages = HTMLHint.default.verify('<ul><li></ul>', {'tag-pair': true});
  console.log(messages)
</script>
```

See https://github.com/htmlhint/HTMLHint/wiki/Usage
