### ISSUE TITLE
Special characters must be escaped

### ISSUE THREAD

**Issue by itlen** [htmlhint/HTMLHint#283]
Linter report trouble in escaping double slash, but in real it's space character before «content=» in 
<meta name="twitter:url"content="//example.com/page.html" >

**Comment by thedaviddias** [comment]
Thanks @itlen for reporting the issue, I think someone else already reports that kind of issue. We'll look into this.

**Comment by Arcanemagus** [comment]
Looks like this is likely a duplicate of #165.
