### ISSUE TITLE
Print a warning if csslint/jshint rules are provided but the tools aren't installed

### ISSUE THREAD

**Issue by waldyrious** [htmlhint/HTMLHint#298]
**Is your feature request related to a problem? Please describe.**
Following the merge of #284, jshint and csslint are no longer installed along with htmlhint, but htmlhint's configuration file still accepts jshint and csslint rules.

If a config file does include such rules but csslint/jshint haven't been manually  installed, then htmlhint will report that the files were checked against the rules specified in the configuration file, and report that there are no css/js issues.

**Describe the solution you'd like**
htmlhint should warn the user that csslint and/or jshint rules will be ignored because the corresponding package is not installed, rather than silently claim there are no errors.

**Describe alternatives you've considered**
A possibly nicer workflow could be for htmlhint to ask the user if they want to install the necessary dependency, and do it if they say so, and only then run the checks on the file.

**Additional context**
Please see the thread at #284 for the discussion leading up to this issue.

**Comment by waldyrious** [comment]
I still think this is worthwhile.

**Comment by Shinigami92** [comment]
Not really anymore, because we will remove and replace csslint and jshint with stylelint and eslint #213

We may think about to add or add not warnings for them

**Comment by waldyrious** [comment]
Warnings for stylelint and eslint not being present would still be worthwhile IMO.

**Comment by Shinigami92** [comment]
> Warnings for stylelint and eslint not being present would still be worthwhile IMO.

Yes, but I think that could be covered by #213 

So maybe this issue is a duplicate now and we can close it? 🤔 

What do you think? @waldyrious

**Comment by waldyrious** [comment]
> that could be covered by #213

It could, but that would mean overloading two changes into the same issue. Even though they're related, I don't think it makes sense to e.g. block that issue from being closed if the tool replacement is made but the warnings for when they're missing are not added; so I think it makes sense to have separate issues for each scope and to keep things more modular and easier to tackle progressively.

**Comment by Shinigami92** [comment]
I think you missed the fact that we already stopped supporting `jshint` / `csslint` in the current version
So it makes no difference whether we add a warning directly while implementing `eslint` / `stylelint` or make an additional commit afterwards
