### ISSUE TITLE
The provided node_modules code should not be made illegible

### ISSUE THREAD

**Issue by Shinigami92** [htmlhint/HTMLHint#302]
**Is your feature request related to a problem? Please describe.**
If you install HTMLHint over npm and look in the `node_modules/lib/...` folder, you will not be able to read the code.
This is NOT developer friendly and not the way other package providers provide code there.

Additional side note: Many files are included which are unnecessary. Even a complete `node_modules` folder under `node_modules/htmlhint/node_modules` :thinking: 

**Describe the solution you'd like**
Provide readable code

**Describe alternatives you've considered**
There is no alternative

**Additional context**
![workspace 1_080](https://user-images.githubusercontent.com/7195563/45076655-410d6480-b0eb-11e8-8482-3662294f4499.png)

**Comment by Shinigami92** [comment]
@olore Can you please explain what you do not like (and do not just give it a thumbs down)

**Comment by olore** [comment]
Hi @Shinigami92. My apologies. After thinking about it a bit, I have reconsidered my position. I agree, HTMLHint should deliver both a minified and a full source JS file.

Regarding the 2nd part - have you identified specific packages that shouldn't be installed as dependencies? Can you please list them.

**Comment by Shinigami92** [comment]
### Following files can be removed (red underlined):

![selection_081](https://user-images.githubusercontent.com/7195563/45215632-5e366480-b29e-11e8-9faa-f9f032f0c3e8.png)

This is the content of `myproject/node_modules/htmlhint` after a fresh `npm install`

**Comment by Shinigami92** [comment]
We have to reevaluate this after doing some cleanup
