### ISSUE TITLE
Whitespace inside attribute

### ISSUE THREAD

**Issue by AbdealiJK** [htmlhint/HTMLHint#310]
**Is your feature request related to a problem? Please describe.**
Many times, people add unnecessary whitespaces inside some attributes. For example `class=" col-md-2"` and sometimes double space between values in the `class` attribute `class="col-md-2  col-offset-2`
Would be nice to give a warning in such cases

**Describe the solution you'd like**
Would be good to have a rule for "No leading/training spaces in attribute" and maybe another one specifically for `class` attribute to handle that all values should be separated by a single space

**Describe alternatives you've considered**
NA

**Comment by nebulousdog** [comment]
@AbdealiJK I think this was implemented in https://github.com/htmlhint/HTMLHint/pull/322.
