### ISSUE TITLE
move `snyk` to devDependencies

### ISSUE THREAD

**Issue by QuentinFchx** [htmlhint/HTMLHint#313]
**Is your feature request related to a problem? Please describe.**
Currently `snyk` and all its dependencies are downloaded when using `htmlhint` while it does not seem to be a core requirement.

**Describe the solution you'd like**
move `snyk` to `devDependencies`

**Comment by NewFuture** [comment]
waiting for update & release

**Comment by thedaviddias** [comment]
@NewFuture new version 0.10.2
