### ISSUE TITLE
community standards for creating custom HTMLHint rules

### ISSUE THREAD

**Issue by nebulousdog** [htmlhint/HTMLHint#314]
Are there any community standards for creating custom HTMLHint rules? Thanks!

**Comment by nebulousdog** [comment]
For example, any tips on when to remove event listeners?

**Comment by Shinigami92** [comment]
I'm thinking about adding a tutorial to our new [documentation website](https://htmlhint.com/docs/user-guide/getting-started) 🤔 

What do you think @thedaviddias?

**Comment by nebulousdog** [comment]
maybe we should turn stale-bot off during the pandemic.
