### ISSUE TITLE
id-class-value being fired by id containing interpolation (angular related)

### ISSUE THREAD

**Issue by ghaschel** [htmlhint/HTMLHint#320]
**Is your feature request related to a problem? Please describe.**
It frustrates me when making interpolated ids on angular. It always fires up `id-class-value`.

**Describe the solution you'd like**
It would be nice to have an option to allow `{{variable}}` alongside the already existent configuration.

**Describe alternatives you've considered**
maybe adding an option like `allow-interpolated-attr-content` that would activate the above mentioned behaviour

**Additional context**
![image](https://user-images.githubusercontent.com/5878866/54536386-64a14980-496f-11e9-897a-2691df1baa4b.png)

**Comment by ghaschel** [comment]
Still happening ='(

**Comment by sebfie** [comment]
Same issue
