### ISSUE TITLE
TypeError: HTMLHint.verify is not a function

### ISSUE THREAD

**Issue by wangchit** [htmlhint/HTMLHint#342]
Why do I get this error? 
var HTMLHint  = require('htmlhint').HTMLHint;
var messages = HTMLHint.verify(cleaned, {'tag-pair': true}); <= error is thrown here.

**Comment by meetDeveloper** [comment]
@wangchit This is an extremely important issue that will make the whole application redundant, kindly check into it, I am also facing the same issue.

**Comment by meetDeveloper** [comment]
@wangchit It should be 
`var HTMLHint = require('htmlhint').default;`

Their documentation is wrong.

**Comment by meetDeveloper** [comment]
Opening.
