### ISSUE TITLE
Update CHANGELOG.md

### ISSUE THREAD

**Issue by coliff** [htmlhint/HTMLHint#349]
Would be good to update CHANGELOG.md as there have been some releases (https://github.com/htmlhint/HTMLHint/releases) since it was last updated. If maintaining a separate CHANGELOG.md is too much extra work then instead could consider removing the list of changes and instead have a note that says to check https://github.com/htmlhint/HTMLHint/releases.

That is the approach that the Bootstrap 3 GitHub Repo took: https://github.com/twbs/bootstrap/blob/v3-dev/CHANGELOG.md

**Comment by thedaviddias** [comment]
Thanks @coliff to point that out. A lot needs to be done to improve the project. I'm planning some weekends to go throught everything that needs to be done.

**Comment by Shinigami92** [comment]
Bumb to prevent from stale

The CHANGELOG.md is still from 3.Sep.2018

**Comment by Shinigami92** [comment]
Now we have an automatic changelog

Should we update the lower part of the changelog to reflect the automatic style?
