### ISSUE TITLE
False positive for right angle bracket ">"

### ISSUE THREAD

**Issue by montao** [htmlhint/HTMLHint#361]
**Describe the bug**
I am not a front-end expert but If I understand correctly, the right angle bracket ">" is not necessary to escape in HTML or XML. 
**To Reproduce**
1. Go to htmlhint.com
2. Paste in some HTML which contains a text with ">" for example` <!DOCTYPE html><html lang="en"><head><title>Hello</title></head><body><p>Hello > World</p></body></html>`
The above HTML actually validates with no errors with https://validator.w3.org/ (whereas the unescaped left angle bracket "<" fails validation as expected with w3.org ` <!DOCTYPE html><html lang="en"><head><title>Hello</title></head><body><p>Hello < World</p></body></html>`
3. It complains about the ">"

**Expected behavior**
It should maybe not complain about unescaped right angle bracket. 
Info https://stackoverflow.com/questions/7389867/is-it-necessary-to-html-encode-right-angle-brackets

**Comment by revelt** [comment]
In general, at least three characters are always encoded: both brackets and ampersand. The main concern is security — if you leave raw brackets, they might be used against you. Conceptually, we're talking about some lint-worthy web page, likely a web application — if so, raw bracket will be used against you. See https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet
