### ISSUE TITLE
How do you exclude JSHint and CSS Lint?

### ISSUE THREAD

**Issue by sanjade** [htmlhint/HTMLHint#365]
I want to just use HTMLHint. Is there a configuration where I can exclude JSHint and CSS Lint?

Currently, I am using HTMLHint like this:

```
import HTMLHint from "htmlhint"

const errors = HTMLHint.verify(val, {
    "tag-pair": true,
    "doctype-first": false,
    "tag-self-close": true,
    "doctype-html5": false
})
```

**Comment by waldyrious** [comment]
I'm not sure if this is still relevant, but [last time I checked](https://github.com/htmlhint/HTMLHint/issues/56) the JSHint and CSSLint options did nothing by default. Maybe the tool's behavior has changed since then?

**Comment by SanjayBanjade** [comment]
In `rules/index.js`, css lint and js hint are both imported by default so I guess there’s no way to exclude both of em’ for now.

**Comment by thedaviddias** [comment]
@sanjade JSHint and CSSLint will be probably removed in one of the next releases.

**Comment by Shinigami92** [comment]
We want to replace jshint and csslint https://github.com/htmlhint/HTMLHint/issues/213

**Comment by Shinigami92** [comment]
We need to remove the `jshint` and `csslint` doc parts
