### ISSUE TITLE
Exception after upgrading to htmlhint 0.12.0

### ISSUE THREAD

**Issue by doberkofler** [htmlhint/HTMLHint#372]
**Describe the bug**

Javascript exception whentrying to run htmlhint 0.12.0:
```bash
/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/htmlhint/dist/htmlhint.js:95
          return f;
          ^^^^^^

SyntaxError: Unexpected token 'return'
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 81

**Comment by hubby2004** [comment]
Same issue on a different OS: 

Desktop (please complete the following information):

OS: Windows 10.0.14393
Visual Code 1.37.0
Node.js: 10.11.0

**Comment by mobilemind** [comment]
same issue on CLI with `htmlhint -V`

htmlhint@0.12.0 
macOS: 10.15.4 
node: v14.2.0
npm: 6.14.5

**Comment by thijstriemstra** [comment]
Unable to upgrade to 0.12.0 with this error. htmlhint is completely broken right now, can we have a new release?

**Comment by thedaviddias** [comment]
@thijstriemstra A PR #381 has been open if you want to take a look. It should fix the issue. 🙂

**Comment by simon-rade-n8** [comment]
I think **0.12.1** doesn't work either. I think htmlhint.js file is expected, htmlhint.min.js present.
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../dist/htmlhint.js'
```

**Comment by thedaviddias** [comment]
@simon-rade-n8 my bad, I'm gonna fix this, need to update the rollup config.

**Comment by thedaviddias** [comment]
@simon-rade-n8 @doberkofler can you confirm that the issue is gone with the last release? 🙏

**Comment by doberkofler** [comment]
Yes, the problem is gone. Thank you!
