### ISSUE TITLE
Keep CHANGELOG.md updated

### ISSUE THREAD

**Issue by feenes** [htmlhint/HTMLHint#374]
Normally CHANGELOG.md should be updated for each release.

CHANGELOG.md wasn't change within the last two years.

CHANGELOG.md contains usually for each release a summary of the changes since the previous release and it could even allow to quickly see the involved commits and make a diff if
the title for each version looks like:

```
## [v0.9.13](https://github.com/htmlhint/HTMLHint/compare/v0.9.12...v0.9.13)
```
instead of 
```
## ver 0.9.13 (2016-5-1)
```
and if releases v0.9.12 and v0.9.13 have a tag

**Comment by diegocr** [comment]
Fully agree here, moreover tome it was kinda suspicious the last release... and then applying some security fix afterwards, how about a new proper release now? just saying :)

**Comment by thedaviddias** [comment]
@feenes @diegocr A few mistakes were done in previous releases, I'm trying to fix these this week. Semantic release is going to automatically update the changelogs and create a more automatic release process. I'm sorry for these inconveniences but they will be fixed in the next days.
