### ISSUE TITLE
How to stop htmlhint from linting markdown files? 

### ISSUE THREAD

**Issue by jtheletter** [htmlhint/HTMLHint#446]
**Describe the bug**

I'm seeing flags raised in `readme.md` files, such as this: 

```
htmlhint: error
doctype-first - Doctype must be declared first.
```

And:

```
htmlhint: error
spec-char-escape - Special characters must be escaped : [ > ].
```

htmlhint is properly linting `*.html` files. It's not mis-linting other files, such as `*.css` and `*.js`. 

Why is it linting markdown files?

If I'm required to exclude them, how do I? Should I add a file to my machine's home directory, such as `~/.htmlhint`? What should it say? The following don't work:

```
{
    "exclude": ["*.md"]
}
```

```
{
    "exclude": ["**/*.md"]
}
```

* macOS Catalina Version 10.15.4 (19E287)
* Sublime Text Version 3.2.2, Build 3211
* htmlhint --version 0.10.1

**Comment by thedaviddias** [comment]
@jtheletter are you using the sublime text plugin or just htmlhint CLI?

**Comment by Shinigami92** [comment]
```json
{
  "exclude": []
}
```

This is currently not implemented: see #279 

---

Does CLI give the same result?
Otherwise please open an issue in https://github.com/htmlhint/SublimeLinter-contrib-htmlhint/issues

**Comment by thedaviddias** [comment]
HTMLHint core is currently on version `0.14.0`, we may need to update our plugin https://github.com/htmlhint/SublimeLinter-contrib-htmlhint, could you create an issue in the specific repo?

**Comment by jtheletter** [comment]
Issue now created here: https://github.com/htmlhint/SublimeLinter-contrib-htmlhint/issues/19

**Comment by thedaviddias** [comment]
We're gonna take a look, thanks @jtheletter!
