### ISSUE TITLE
Docs `attr-lowercase` has incorrect violation example (easy fix)

### ISSUE THREAD

**Issue by tag** [htmlhint/HTMLHint#531]
/docs/user-guide/rules/attr-lowercase.md

Both "valid" and "violation" examples on the docs page appear to show the same HTML snippet:
```html
<img src="test.png" alt="test" />
```

I'm guessing the violation example should be something like:
```html
<img SRC="test.png" ALT="test" />
```

**Comment by waldyrious** [comment]
I've submitted #564 to fix this.
