### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by aravindvnair99** [htmlhint/HTMLHint#645]
```console
$ npm i -g htmlhint@latest
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

**Comment by thedaviddias** [comment]
Hey @aravindvnair99, thanks for pointing that out. The repo is going to be updated in the coming days. Hopefully, you will not see these messages in the near future.

**Comment by aravindvnair99** [comment]
> Hey @aravindvnair99, thanks for pointing that out. The repo is going to be updated in the coming days. Hopefully, you will not see these messages in the near future.

@thedaviddias Any updates?

**Comment by aravindvnair99** [comment]
As of today, 25th July 2021:

```console
$ npm i -g htmlhint@latest
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 75 packages, and audited 76 packages in 11s

5 packages are looking for funding
  run `npm fund` for details

4 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

Version is `0.15.1`

**Comment by stuartbale** [comment]
request is used in one place - the HtmlHint CLI.

https://github.com/htmlhint/HTMLHint/blob/ebaea6c5a51b977d3517e77477915f1d37e9fc52/src/cli/htmlhint.ts#L497

If someone can post what the suggested replacement for this is, I can submit a pull request.

**Comment by stuartbale** [comment]
> request is used in one place - the HtmlHint CLI.
> 
> https://github.com/htmlhint/HTMLHint/blob/ebaea6c5a51b977d3517e77477915f1d37e9fc52/src/cli/htmlhint.ts#L497
> 
> If someone can post what the suggested replacement for this is, I can submit a pull request.
> 
> Replacing request will resolve all three deprecated warnings.

Would node-fetch be suitable?

https://www.npmjs.com/package/node-fetch

Seems to be well supported and used in >21k other packages.

**Comment by stuartbale** [comment]
I notice a pending Pull Request with a fix for this here:
https://github.com/htmlhint/HTMLHint/pull/670

**Comment by darcyparker** [comment]
with #670 merged, can this be closed?
