### ISSUE TITLE
html-lang-require should allow just language (not require region)

### ISSUE THREAD

**Issue by coliff** [htmlhint/HTMLHint#652]
**Describe the bug**

HTMLHint 0.15.0 adds the `html-lang-require` rule. This requires both a language and a region to be set, however it is perfectly valid to use just a language on a webpage, for example `<html lang="en">` should be marked as valid. The region subtag is optional.

REF:

- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang
- https://en.wikipedia.org/wiki/IETF_language_tag

**To Reproduce**

Run htmlhint on a webpage with `<html lang="en">`

**Screenshots**

![image](https://user-images.githubusercontent.com/1212885/121635416-29940f00-cac1-11eb-9634-eec321b7bb4e.png)

cc @baleyko

**Comment by baleyko** [comment]
@coliff fixes are in this PR: #655

**Comment by thedaviddias** [comment]
@coliff Are we good to close this issue?

**Comment by coliff** [comment]
yep. all good now I think 👍
