### ISSUE TITLE
html-lang-require reports lots of false positives

### ISSUE THREAD

**Issue by coliff** [htmlhint/HTMLHint#653]
**Describe the bug**

The `html-lang-require` rule appears to check every single tag when running 

**To Reproduce**

Run `htmlhint index.html` with 0.15.0

**Expected behavior**

Only the `<HTML>` tag should be tested for this rule

**Screenshots**

Partial screenshot form terminal output:

![image](https://user-images.githubusercontent.com/1212885/121637920-200ca600-cac5-11eb-9782-6d750238aed2.png)

cc @baleyko

**Comment by baleyko** [comment]
@coliff I will make a fix today.

**Comment by baleyko** [comment]
fixes are in this PR: #655

**Comment by thedaviddias** [comment]
Thanks @coliff for logging the issue and @baleyko for fixing it so quickly! I believe we can close this ticket now as it was fixed in https://github.com/htmlhint/HTMLHint/pull/655

**Comment by coliff** [comment]
Fixed now - thanks!
