### ISSUE TITLE
Is it possible to look up the outer HTML tag? 

### ISSUE THREAD

**Issue by derpdeveloper** [htmlhint/HTMLHint#654]
Hi HTMLHint Team,

**Describe your problem**
I'm trying to make a rule where HTMLHint reports if there is a wrapper tag outside the ```strong``` tag

**E.g:** 
```html 
<p><strong>Text</strong></p>
```
- HTMLHint should report that there is a wrapper ```p``` tag outside the ```strong``` tag 

**What I've tried**

```javascript
parser.addListener("tagend", function (event) {
          console.log(event)
        });
```
Which logs:
<img width="816" alt="image" src="https://user-images.githubusercontent.com/85733848/121662532-ccac4f00-cae8-11eb-8f67-3fb12856cf6f.png">

However I'm not able to get the ```</p>``` event that comes after the ```</strong/>``` event

**Comment by thedaviddias** [comment]
Hey @derpdeveloper, could you explain why a `<p>` wrapping a `<strong>` tag will be an error? I may be missing something here...

**Comment by derpdeveloper** [comment]
> Hey @derpdeveloper, could you explain why a `<p>` wrapping a `<strong>` tag will be an error? I may be missing something here...

Hi @thedaviddias, thanks for replying.

No this is not an error, I'm making this custom rule only for personal use where I want to find all the ```<strong>``` tags whose text starts with "Figure:" in a big content static site. 

This is because there are some cases where two or more ```<strong>``` tags are wrapped in the same ```<p>```, making them in the same line which is what I don't want.
