### ISSUE TITLE
`.htmlhintrc` silently ignored if not valid JSON

### ISSUE THREAD

**Issue by estrehle** [htmlhint/HTMLHint#662]
If the `.htmlhintrc` is not valid JSON, the linter silently ignores it and uses a default config.

For example, I had made the mistake of keeping a trailing comma:

    {
        "attr-lowercase": false,
    }

The default config has `"attr-lowerclase": true` and I received a lot of unwanted errors. It took me a while to figure out that the malformatted JSON was the culprit.

It would be helpful if the linter at least displayed a warning log message upon execution if it cannot parse the config file.

**Comment by marwinburesch** [comment]
I agree, for example the docs [use single quotes in the examples](https://htmlhint.com/docs/user-guide/rules/attr-lowercase), but it is only valid with double quotes
