### ISSUE TITLE
Update Prettier?

### ISSUE THREAD

**Issue by coliff** [htmlhint/HTMLHint#682]
Prettier is locked to "2.0.5" in package.json but later releases have many improvements and bug fixes. Can we update to the latest "2.4.0"?

And then maybe add the 'bracketSameLine': true option to the config? (makes HTML files neater)
https://prettier.io/blog/2021/09/09/2.4.0.html#html

**Comment by thedaviddias** [comment]
👍 Sure, feel free to open a PR for that!

**Comment by coliff** [comment]
Maybe we should just add  a "^" before the version number in package.json and let dependabot take care of it...
