### ISSUE TITLE
[new rule] Max attributes for single line tags.

### ISSUE THREAD

**Issue by viniciusdacal** [htmlhint/HTMLHint#89]
We could have an option to limit the number of attributes for single line tags
Example: limit 4 attr.
this would be correct:

```
<input type="text" name="test" id="test" maxlength="10">
```

but this, would be wrong

```
<input type="text" name="test" id="test" maxlength="10" class="form-control">
```

to correct the above tag , we could write this way:

```
<input
    type="text"
    name="test"
    id="test"
    maxlength="10"
    class="form-control"
    >
```

or, this way (but I prefer that way, to avoid extras diffs when adding a new last attribute)

```
<input
    type="text"
    name="test"
    id="test"
    maxlength="10"
    class="form-control">
```

**Comment by yaniswang** [comment]
I don't think single line for tags is better habit.

**Comment by hamxabaig** [comment]
I think it's good, as when we write so many `attributes` on one single line then comes up the horizontal scrollbar and its difficult to view html files which are horizontally long. 

Think as JSX, where we don't write multiple props (attributes) on different lines.

We don't have to split it to one attribute per line we can also do something like below and that makes sense to me i guess.
```
<input
    type="text" name="test" id="test"
    maxlength="10" class="form-control"
>
```
My idea is to avoid long lines and split many attributes of single element to multiple lines.
As we've `max-len` in ESLINT I think would be better if we can have something like this in HTML hint also.

Thanks

**Comment by darxx** [comment]
Some good example: https://github.com/htmlhint/HTMLHint/issues/89.
