### ISSUE TITLE
"env: node\r: No such file or directory"

### ISSUE THREAD

**Issue by mattfordham** [htmlhint/HTMLHint#9]
I get this error when attempting to run "htmlhint" from the command line. I installed with "npm install htmlhint -g". Any ideas?

**Comment by focusaurus** [comment]
Can you please publish an updated version to npm with this fix? This issue is still affecting new installs.

**Comment by morganpolotan** [comment]
A fix pushed to npm would be much appreciated, as I'm still seeing this bug. In the meantime, referencing the executable directly works:

`node /usr/local/bin/htmlhint index.html`

**Comment by keik** [comment]
+1
